[install]
# https://bun.sh/docs/runtime/bunfig#package-manager
exact = true
linker = "isolated"
registry = { url = "https://registry.npmjs.org", token = "$NPM_TOKEN" }

[test]
# https://bun.sh/docs/runtime/bunfig#test-runner
coverage = true
coveragePathIgnorePatterns = ["**/dist/**", "test-preload.ts"]
coverageThreshold = 0.3 # TODO: Raise back to 0.7 (packages/core/src/debug.ts, packages/core/src/arrayInstrumentations.ts, lib/src/utils.ts)
preload = ["./test-preload.ts"]
