name: Quality

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v6

      - name: Install
        uses: ./.github/actions/install

      - name: Build packages
        run: bun run build

  tests:
    name: Tests
    env:
      DEV: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v6

      - name: Install
        uses: ./.github/actions/install

      - name: Run tests
        run: bun test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v6

      - name: Install
        uses: ./.github/actions/install

      - name: Run lint
        run: bun lint
